### ISSUE TITLE
Crashing on load up

### ISSUE THREAD

**Issue by Expora9** [veesusmikelheir/SRML#1]
I've just installed SRML and I loaded the game up and it got the main menu for about 2secs and froze then crashed 

PS: I'm not sure if the installer is offical: here it is 

[SRML.zip](https://github.com/veesusmikelheir/SRML/files/3677898/SRML.zip)

**Comment by veesusmikelheir** [comment]
Not enough information, if the issue persists, contact me on discord for general tech support.
