### ISSUE TITLE
Debug-related class files in SRML/SR/Utils/Debug missing

### ISSUE THREAD

**Issue by abyll** [veesusmikelheir/SRML#2]
Files are not included in git repository, likely from .gitignore configuration set to ignore [Dd]ebug/

SRML/SR/Utils/Debug/
 AddDebugMarker.cs 
 DebugCommand.cs
 DebugMarker.cs
 DebugSystem.cs
 MarkerType.cs

**Comment by veesusmikelheir** [comment]
Fixed! Sorry for the late response!
